export const SET_SEARCH_BAR = "SET_SEARCH_BAR";

export const FETCH_CATALOGUE = "FETCH_CATALOGUE";

export const SET_CATALOGUE_IS_LOADING = "SET_CATALOGUE_IS_LOADING";

export const SET_CATALOGUE_IS_NOT_LOADING = "SET_CATALOGUE_IS_NOT_LOADING";

export const SAVE_CATALOGUE = "SAVE_CATALOGUE";
